name: Deploy to AWS

on:
  workflow_dispatch:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: "./auth"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: terraform init
        run: make tf-init
      - name: terraform plan
        run: make tf-plan
      - name: terraform apply
        run: make tf-apply